Repository KrlosPK/WebFAM, pull requests merged in 2023-03, with the labels that each got.

#71 admin edits users works
  package.json
  src/App.jsx
  src/components/AllUsers/AllUsers.css
  src/components/AllUsers/AllUsers.jsx
  src/components/AllUsers/EditUser/InfoUserEdit.css
  src/components/AllUsers/EditUser/InfoUserEdit.jsx
  src/components/EditUser/EditUser.jsx
Labels: enhancement

#80 Conan dev
  package-lock.json
  package.json
  src/components/AllUsers/EditUser/InfoUserEdit.jsx
  src/components/EditUser/EditUser.jsx
  src/components/Login/Login.jsx
  src/components/Register/Register.jsx
  src/components/Utils/Button2/Button2.jsx
  src/components/Utils/Navbar/Navbar.jsx
  src/components/Utils/Select/Select.jsx
Labels: bug, enhancement

#88 Cookie login
  package.json
  src/App.jsx
  src/components/AboutUs/AboutUs.jsx
  src/components/AllUsers/AllUsers.jsx
  src/components/AllUsers/EditUser/InfoUserEdit.jsx
  src/components/Citas/CitaDetalle/CitaDetalle.jsx
  src/components/Citas/Citas.jsx
  src/components/EditUser/EditUser.jsx
  src/components/Home/Home.jsx
  src/components/Login/Login.css
  src/components/Login/Login.jsx
  src/components/Services/AddService/AddService.jsx
  src/components/Services/EditService/EditService.jsx
  src/components/Services/Service/Service.jsx
  src/components/Services/Services.jsx
  src/components/Utils.js
  src/components/Utils/GetToken/GetToken.js
  src/components/Utils/ModalService/ModalService.jsx
  src/components/Utils/Navbar/Navbar.jsx
  src/components/Utils/ResponsiveNav/ResponsiveNav.jsx
  src/components/Utils/Token.jsx
  src/context/SessionContext.jsx
Labels: enhancement

#89 10% mis agendas
  src/App.jsx
  src/components/Citas/CitasUser/CitasUser.css
  src/components/Citas/CitasUser/CitasUser.jsx
  src/components/EditUser/EditUser.jsx
  src/components/Home/Home.jsx
  src/components/Services/Service/Service.jsx
  src/components/Services/Services.jsx
Labels: enhancement

#90 Citas section
  .eslintrc.json
  package.json
  public/aparejo.png
  public/crisol.png
  public/metal.png
  public/service-aparejo.png
  public/service-caseta.png
  public/service-cubierta.png
  public/service-mezanine.png
  public/service-pergola.png
  public/soldador.png
  src/components/AboutUs/AboutUs.jsx
  src/components/Citas/CitaDetalle/CitaDetalle.jsx
  src/components/Citas/CitasUser/CitasUser.css
  src/components/Citas/CitasUser/CitasUser.jsx
  src/components/EditUser/EditUser.jsx
  src/components/Home/Home.css
  src/components/Home/Home.jsx
  src/components/Login/Login.jsx
  src/components/Services/Service/Service.css
  src/components/Services/Service/Service.jsx
  src/components/Services/Services.jsx
  src/components/Utils/ModalService/ModalService.jsx
  src/components/Utils/ResponsiveNav/ResponsiveNav.css
  src/components/Utils/ResponsiveNav/ResponsiveNav.jsx
  src/json/services.json
Labels: documentation, enhancement

#91 Citas section
  package.json
  src/components/AllUsers/EditUser/InfoUserEdit.jsx
  src/components/Citas/Citas.css
  src/components/Citas/Citas.jsx
  src/components/EditUser/EditUser.jsx
  src/components/Home/Footer/Footer.jsx
  src/components/Home/Home.css
  src/components/Login/RecoverPassword/RecoverPassword.jsx
  src/components/Login/ResetPassword/ResetPassword.jsx
  src/components/Not-found/NotFound.jsx
  src/components/Services/Service/Service.css
  src/components/Services/Service/Service.jsx
  src/components/Utils/LongCard/LongCard.jsx
  src/components/Utils/ModalService/ModalService.jsx
  src/components/Utils/Navbar/Navbar.jsx
  src/components/Utils/ResponsiveNav/ResponsiveNav.jsx
Labels: bug

#93 Citas section
  src/components/EditUser/EditUser.css
  src/components/Utils/ModalService/ModalService.jsx
Labels: bug

#94 buttons changes
  src/components/AboutUs/AboutUs.jsx
  src/components/Utils/Button/Button.jsx
  src/components/Utils/Button2/Button2.jsx
  src/components/Utils/Card/Card.css
  src/components/Utils/Card/Card.jsx
Labels: enhancement

#95 Citas section
  package.json
  src/components/AllUsers/EditUser/InfoUserEdit.jsx
  src/components/Services/Service/Service.jsx
  src/components/Utils/LongCard/LongCard.css
  src/components/Utils/LongCard/LongCard.jsx
  src/components/Utils/ModalService/ModalService.jsx
  src/components/Utils/ResponsiveNav/ResponsiveNav.jsx
  src/components/Utils/TextArea/TextArea.css
Labels: bug

#96 Citas section
  package.json
  src/components/Citas/Cita.jsx
  src/components/Citas/Citas.jsx
  src/components/Utils/Select/Select.jsx
Labels: enhancement, help wanted

#97 Citas section
  package.json
  src/components/Citas/Cita.jsx
  src/components/Citas/Citas.css
  src/components/Citas/CitasUser/CitasUser.css
  src/components/Home/Footer/Footer.css
  src/components/Home/Footer/Footer.jsx
  src/components/Utils/LongCard/LongCard.css
Labels: bug, enhancement, good first issue

#98 if user has a pending date, can't schedule date
  package.json
  src/components/Citas/Cita.jsx
  src/components/Citas/Citas.jsx
  src/components/Services/Service/Service.jsx
  src/components/Utils/ModalService/ModalService.jsx
Labels: enhancement, help wanted

#99 cita detalle responder button
  package.json
  src/components/Citas/Cita.jsx
  src/components/Citas/CitaDetalle/CitaDetalle.css
  src/components/Citas/CitaDetalle/CitaDetalle.jsx
  src/components/Citas/Citas.jsx
  src/components/Utils/LongCard/LongCard.css
Labels: enhancement

#100 v0.31.0
  package-lock.json
  package.json
  src/components/AboutUs/AboutUs.css
  src/components/AboutUs/AboutUs.jsx
  src/components/Citas/Citas.jsx
  src/components/Citas/CitasUser/CitasUser.css
  src/components/Citas/CitasUser/CitasUser.jsx
  src/components/Services/EditService/EditService.css
  src/components/Services/EditService/EditService.jsx
  src/components/Services/Services.jsx
  src/components/Utils/TextArea/TextArea.css
Labels: enhancement

#101 send admin email for each new date
  package.json
  src/components/Utils/ModalService/ModalService.jsx
Labels: enhancement, help wanted

#103 v0.33.1
  package.json
  src/components/Citas/Citas.jsx
  src/components/Citas/CitasUser/CitasUser.jsx
Labels: enhancement

#102 Citas section
  package-lock.json
  package.json
  src/components/Citas/Citas.jsx
Labels: bug, enhancement

#104 user can't register a number as name or lastname
  src/components/AllUsers/EditUser/InfoUserEdit.jsx
  src/components/EditUser/EditUser.jsx
  src/components/Register/Register.jsx
  src/components/Utils/ModalService/ModalService.jsx
Labels: bug

#105 Conan dev
  package.json
  src/components/AboutUs/AboutUs.css
  src/components/AboutUs/AboutUs.jsx
  src/components/Citas/Citas.jsx
  src/components/Citas/CitasUser/CitasUser.css
  src/components/Citas/CitasUser/CitasUser.jsx
  src/components/EditUser/EditUser.jsx
  src/components/Home/Home.jsx
  src/components/Login/Login.jsx
  src/components/Services/AddService/AddService.jsx
  src/components/Services/EditService/EditService.jsx
  src/components/Services/Service/Service.css
  src/components/Services/Service/Service.jsx
  src/components/Services/Services.jsx
  src/components/Utils/Card/Card.css
  src/components/Utils/Card/Card.jsx
Labels: bug, enhancement, invalid

#106 Validate trim
  package.json
  src/components/AllUsers/EditUser/InfoUserEdit.jsx
  src/components/EditUser/EditUser.jsx
  src/components/Login/Login.jsx
  src/components/Login/ResetPassword/ResetPassword.jsx
  src/components/Register/Register.jsx
Labels: bug

#107 Conan dev
  package.json
  src/components/Login/ResetPassword/ResetPassword.jsx
  src/components/Services/AddService/AddService.jsx
Labels: enhancement

#109 validate in edit service file size
  package.json
  src/components/AllUsers/EditUser/InfoUserEdit.jsx
  src/components/EditUser/EditUser.jsx
  src/components/Services/AddService/AddService.jsx
  src/components/Services/EditService/EditService.jsx
Labels: bug

#110 fix images bug
  package.json
  src/components/AllUsers/EditUser/InfoUserEdit.jsx
  src/components/EditUser/EditUser.jsx
  src/components/Services/AddService/AddService.jsx
  src/components/Services/EditService/EditService.jsx
  src/components/Services/Service/Service.jsx
  src/components/Utils/Card/Card.css
Labels: bug

#111 improve footer
  package.json
  src/components/Home/Footer/Footer.css
  src/components/Home/Footer/Footer.jsx
Labels: enhancement, good first issue

#112 v1.3.0
  package.json
  src/components/AboutUs/AboutUs.jsx
  src/components/Services/Services.jsx
  src/components/Utils/Card/Card.css
  src/components/Utils/Card/Card.jsx
  src/components/Utils/ModalService/ModalService.css
  src/components/Utils/ModalService/ModalService.jsx
Labels: enhancement

#113 Carlos dev
  package.json
  src/App.jsx
  src/components/FAQ/AddFAQ/AddFAQ.jsx
  src/components/FAQ/EditFAQ/EditFAQ.jsx
  src/components/FAQ/FAQ.css
  src/components/FAQ/FAQ.jsx
  src/components/FAQ/FAQStyle.js
  src/components/Home/FrequentQuestions/FrequentQuestions.css
  src/components/Home/FrequentQuestions/FrequentQuestions.jsx
  src/components/Services/EditService/EditService.jsx
  src/components/Utils/Accordion/Accordion.css
  src/components/Utils/TextArea/TextArea.css
  src/components/Utils/TextArea/TextArea.jsx
  src/index.css
  src/json/team.json
Labels: enhancement, help wanted
